name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the rust code
        run : cargo build --verbose
      - name: Run the tests
        run : cargo test --verbose
